# ShivaShield XDP — Build System
#
# Targets:
#   make all       — generate vmlinux.h + BPF bindings + build binary
#   make vmlinux   — generate vmlinux.h from kernel BTF
#   make generate  — run bpf2go to compile C → BPF object + Go bindings
#   make build     — compile the Go binary
#   make clean     — remove generated files
#   make install   — install to /opt/shivashield
#
# Requirements:
#   - Linux 5.15+ with BTF
#   - clang, llvm-strip, bpftool
#   - Go >= 1.22

.PHONY: all vmlinux generate build clean install

BINARY      := shivashield
BIN_DIR     := bin
BPF_C       := ebpf/shivashield.bpf.c
VMLINUX_H   := ebpf/headers/vmlinux.h
GO_MAIN     := ./cmd/shivashield
GO_MODULE   := github.com/shivashield/shivashield-xdp
VERSION     := 1.0.0
LDFLAGS     := -s -w -X main.version=$(VERSION)

# ── all ─────────────────────────────────────────────────────────────

all: vmlinux generate build
	@echo ""
	@echo "  ✓ ShivaShield XDP $(VERSION) built successfully"
	@echo "  Binary: $(BIN_DIR)/$(BINARY)"
	@echo ""

# ── vmlinux.h ───────────────────────────────────────────────────────

vmlinux: $(VMLINUX_H)

$(VMLINUX_H):
	@echo "[*] Generating vmlinux.h from kernel BTF..."
	@mkdir -p ebpf/headers
	bpftool btf dump file /sys/kernel/btf/vmlinux format c > $(VMLINUX_H)
	@echo "[*] vmlinux.h generated ($(shell wc -l < $(VMLINUX_H) 2>/dev/null || echo '?') lines)"

# ── generate (bpf2go) ──────────────────────────────────────────────

generate: $(VMLINUX_H)
	@echo "[*] Downloading Go dependencies..."
	go mod tidy
	go install github.com/cilium/ebpf/cmd/bpf2go@v0.16.0
	@echo "[*] Running bpf2go (compiling C → BPF bytecode + Go bindings)..."
	go generate ./...
	@echo "[*] BPF generation complete"

# ── build ───────────────────────────────────────────────────────────

build:
	@echo "[*] Building $(BINARY)..."
	@mkdir -p $(BIN_DIR)
	CGO_ENABLED=0 go build -ldflags "$(LDFLAGS)" -o $(BIN_DIR)/$(BINARY) $(GO_MAIN)
	cp -f shivashield_x86_bpfel.o $(BIN_DIR)/shivashield.bpf.o 2>/dev/null || true
	@echo "[*] Built: $(BIN_DIR)/$(BINARY) ($(shell ls -lh $(BIN_DIR)/$(BINARY) | awk '{print $$5}'))"

# ── install ─────────────────────────────────────────────────────────

install: all
	@echo "[*] Installing to /opt/shivashield..."
	install -d /opt/shivashield /etc/shivashield
	install -m 0755 $(BIN_DIR)/$(BINARY) /opt/shivashield/$(BINARY)
	# Copy the BPF object (generated by bpf2go, embedded in binary, but
	# we also keep a standalone copy for debugging).
	-cp shivashield_bpfel.o /opt/shivashield/shivashield.bpf.o 2>/dev/null || true
	ln -sf /opt/shivashield/$(BINARY) /usr/local/bin/$(BINARY)
	@echo "[*] Installed: /usr/local/bin/$(BINARY) → /opt/shivashield/$(BINARY)"
	# Install example config if no config exists.
	@if [ ! -f /etc/shivashield/shivashield.yaml ]; then \
		install -m 0600 configs/shivashield.example.yaml /etc/shivashield/shivashield.yaml; \
		echo "[*] Config installed: /etc/shivashield/shivashield.yaml"; \
	else \
		echo "[!] Config already exists, not overwriting"; \
	fi
	# Install systemd service.
	install -m 0644 systemd/shivashield.service /etc/systemd/system/
	systemctl daemon-reload
	@echo "[*] Systemd service installed"
	@echo "[*] Done. Run: sudo systemctl enable --now shivashield"

# ── clean ───────────────────────────────────────────────────────────

clean:
	@echo "[*] Cleaning..."
	rm -f shivashield_bpf*.go shivashield_bpf*.o
	rm -rf $(BIN_DIR)
	rm -f $(VMLINUX_H)
	@echo "[*] Clean"

# ── help ────────────────────────────────────────────────────────────

help:
	@echo "ShivaShield XDP Build System"
	@echo ""
	@echo "Targets:"
	@echo "  all       Build everything (default)"
	@echo "  vmlinux   Generate vmlinux.h from kernel BTF"
	@echo "  generate  Compile BPF C → bytecode + Go bindings"
	@echo "  build     Compile Go binary"
	@echo "  install   Install to /opt/shivashield"
	@echo "  clean     Remove generated files"
	@echo "  help      Show this help"
